// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/carbrand.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarBrand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarBrand) Reset() {
	*x = CarBrand{}
	mi := &file_proto_carbrand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarBrand) ProtoMessage() {}

func (x *CarBrand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarBrand.ProtoReflect.Descriptor instead.
func (*CarBrand) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{0}
}

func (x *CarBrand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CarBrand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CarBrand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListCarBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarBrandsRequest) Reset() {
	*x = ListCarBrandsRequest{}
	mi := &file_proto_carbrand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarBrandsRequest) ProtoMessage() {}

func (x *ListCarBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarBrandsRequest.ProtoReflect.Descriptor instead.
func (*ListCarBrandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{1}
}

type ListCarBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carbrands     []*CarBrand            `protobuf:"bytes,1,rep,name=carbrands,proto3" json:"carbrands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarBrandsResponse) Reset() {
	*x = ListCarBrandsResponse{}
	mi := &file_proto_carbrand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarBrandsResponse) ProtoMessage() {}

func (x *ListCarBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarBrandsResponse.ProtoReflect.Descriptor instead.
func (*ListCarBrandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{2}
}

func (x *ListCarBrandsResponse) GetCarbrands() []*CarBrand {
	if x != nil {
		return x.Carbrands
	}
	return nil
}

type GetCarBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCarBrandRequest) Reset() {
	*x = GetCarBrandRequest{}
	mi := &file_proto_carbrand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCarBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarBrandRequest) ProtoMessage() {}

func (x *GetCarBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarBrandRequest.ProtoReflect.Descriptor instead.
func (*GetCarBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{3}
}

func (x *GetCarBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCarBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCarBrandRequest) Reset() {
	*x = CreateCarBrandRequest{}
	mi := &file_proto_carbrand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCarBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarBrandRequest) ProtoMessage() {}

func (x *CreateCarBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarBrandRequest.ProtoReflect.Descriptor instead.
func (*CreateCarBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCarBrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCarBrandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCarBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCarBrandRequest) Reset() {
	*x = UpdateCarBrandRequest{}
	mi := &file_proto_carbrand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCarBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarBrandRequest) ProtoMessage() {}

func (x *UpdateCarBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarBrandRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCarBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCarBrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCarBrandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteCarBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCarBrandRequest) Reset() {
	*x = DeleteCarBrandRequest{}
	mi := &file_proto_carbrand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCarBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarBrandRequest) ProtoMessage() {}

func (x *DeleteCarBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarBrandRequest.ProtoReflect.Descriptor instead.
func (*DeleteCarBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCarBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCarBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCarBrandResponse) Reset() {
	*x = DeleteCarBrandResponse{}
	mi := &file_proto_carbrand_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCarBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarBrandResponse) ProtoMessage() {}

func (x *DeleteCarBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbrand_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarBrandResponse.ProtoReflect.Descriptor instead.
func (*DeleteCarBrandResponse) Descriptor() ([]byte, []int) {
	return file_proto_carbrand_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCarBrandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_carbrand_proto protoreflect.FileDescriptor

const file_proto_carbrand_proto_rawDesc = "" +
	"\n" +
	"\x14proto/carbrand.proto\x12\bcarbrand\"P\n" +
	"\bCarBrand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x16\n" +
	"\x14ListCarBrandsRequest\"I\n" +
	"\x15ListCarBrandsResponse\x120\n" +
	"\tcarbrands\x18\x01 \x03(\v2\x12.carbrand.CarBrandR\tcarbrands\"$\n" +
	"\x12GetCarBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x15CreateCarBrandRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"]\n" +
	"\x15UpdateCarBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"'\n" +
	"\x15DeleteCarBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteCarBrandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x87\x03\n" +
	"\x0fCarBrandService\x12?\n" +
	"\vGetCarBrand\x12\x1c.carbrand.GetCarBrandRequest\x1a\x12.carbrand.CarBrand\x12P\n" +
	"\rListCarBrands\x12\x1e.carbrand.ListCarBrandsRequest\x1a\x1f.carbrand.ListCarBrandsResponse\x12E\n" +
	"\x0eCreateCarBrand\x12\x1f.carbrand.CreateCarBrandRequest\x1a\x12.carbrand.CarBrand\x12E\n" +
	"\x0eUpdateCarBrand\x12\x1f.carbrand.UpdateCarBrandRequest\x1a\x12.carbrand.CarBrand\x12S\n" +
	"\x0eDeleteCarBrand\x12\x1f.carbrand.DeleteCarBrandRequest\x1a .carbrand.DeleteCarBrandResponseB&Z$ecommerce/car-service/internal/pb;pbb\x06proto3"

var (
	file_proto_carbrand_proto_rawDescOnce sync.Once
	file_proto_carbrand_proto_rawDescData []byte
)

func file_proto_carbrand_proto_rawDescGZIP() []byte {
	file_proto_carbrand_proto_rawDescOnce.Do(func() {
		file_proto_carbrand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carbrand_proto_rawDesc), len(file_proto_carbrand_proto_rawDesc)))
	})
	return file_proto_carbrand_proto_rawDescData
}

var file_proto_carbrand_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_carbrand_proto_goTypes = []any{
	(*CarBrand)(nil),               // 0: carbrand.CarBrand
	(*ListCarBrandsRequest)(nil),   // 1: carbrand.ListCarBrandsRequest
	(*ListCarBrandsResponse)(nil),  // 2: carbrand.ListCarBrandsResponse
	(*GetCarBrandRequest)(nil),     // 3: carbrand.GetCarBrandRequest
	(*CreateCarBrandRequest)(nil),  // 4: carbrand.CreateCarBrandRequest
	(*UpdateCarBrandRequest)(nil),  // 5: carbrand.UpdateCarBrandRequest
	(*DeleteCarBrandRequest)(nil),  // 6: carbrand.DeleteCarBrandRequest
	(*DeleteCarBrandResponse)(nil), // 7: carbrand.DeleteCarBrandResponse
}
var file_proto_carbrand_proto_depIdxs = []int32{
	0, // 0: carbrand.ListCarBrandsResponse.carbrands:type_name -> carbrand.CarBrand
	3, // 1: carbrand.CarBrandService.GetCarBrand:input_type -> carbrand.GetCarBrandRequest
	1, // 2: carbrand.CarBrandService.ListCarBrands:input_type -> carbrand.ListCarBrandsRequest
	4, // 3: carbrand.CarBrandService.CreateCarBrand:input_type -> carbrand.CreateCarBrandRequest
	5, // 4: carbrand.CarBrandService.UpdateCarBrand:input_type -> carbrand.UpdateCarBrandRequest
	6, // 5: carbrand.CarBrandService.DeleteCarBrand:input_type -> carbrand.DeleteCarBrandRequest
	0, // 6: carbrand.CarBrandService.GetCarBrand:output_type -> carbrand.CarBrand
	2, // 7: carbrand.CarBrandService.ListCarBrands:output_type -> carbrand.ListCarBrandsResponse
	0, // 8: carbrand.CarBrandService.CreateCarBrand:output_type -> carbrand.CarBrand
	0, // 9: carbrand.CarBrandService.UpdateCarBrand:output_type -> carbrand.CarBrand
	7, // 10: carbrand.CarBrandService.DeleteCarBrand:output_type -> carbrand.DeleteCarBrandResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_carbrand_proto_init() }
func file_proto_carbrand_proto_init() {
	if File_proto_carbrand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carbrand_proto_rawDesc), len(file_proto_carbrand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_carbrand_proto_goTypes,
		DependencyIndexes: file_proto_carbrand_proto_depIdxs,
		MessageInfos:      file_proto_carbrand_proto_msgTypes,
	}.Build()
	File_proto_carbrand_proto = out.File
	file_proto_carbrand_proto_goTypes = nil
	file_proto_carbrand_proto_depIdxs = nil
}
